
// Objective-C API for talking to the following Go packages
//
//	github.com/kinfkong/ikatago-client/ikatagosdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ikatagosdk_FRAMEWORK_H__
#define __Ikatagosdk_FRAMEWORK_H__

#include "Ikatagosdk.objc.h"
#include "Universe.objc.h"

#endif
