// Objective-C API for talking to github.com/kinfkong/ikatago-client/ikatagosdk Go package.
//   gobind -lang=objc github.com/kinfkong/ikatago-client/ikatagosdk
//
// File is generated by gobind. Do not edit.

#ifndef __Ikatagosdk_H__
#define __Ikatagosdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class IkatagosdkClient;
@class IkatagosdkClientRunner;
@class IkatagosdkKatagoRunner;
@protocol IkatagosdkDataCallback;
@class IkatagosdkDataCallback;

@protocol IkatagosdkDataCallback <NSObject>
- (void)callback:(NSData* _Nullable)content;
- (void)onReady;
- (void)stderrCallback:(NSData* _Nullable)content;
@end

/**
 * Client the client wrapper
 */
@interface IkatagosdkClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewClient creates the new mobile client
 */
- (nullable instancetype)init:(NSString* _Nullable)world platform:(NSString* _Nullable)platform username:(NSString* _Nullable)username password:(NSString* _Nullable)password;
/**
 * CreateKatagoRunner creates  the katago runner
 */
- (IkatagosdkKatagoRunner* _Nullable)createKatagoRunner:(NSError* _Nullable* _Nullable)error;
/**
 * QueryServer queries the server info
 */
- (NSString* _Nonnull)queryServer:(NSError* _Nullable* _Nullable)error;
/**
 * SetEngineType sets the engine type
 */
- (void)setEngineType:(NSString* _Nullable)engineType;
/**
 * SetExtraArgs sets the extra args like "--gpu-type 3x --engine-type katago"
 */
- (void)setExtraArgs:(NSString* _Nullable)extraArgs;
/**
 * SetToken sets the force node
 */
- (void)setForceNode:(NSString* _Nullable)forceNode;
/**
 * SetGpuType sets the gpu type
 */
- (void)setGpuType:(NSString* _Nullable)gpuType;
/**
 * SetToken sets the token
 */
- (void)setToken:(NSString* _Nullable)token;
@end

@interface IkatagosdkClientRunner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)initFromArgs:(NSString* _Nullable)argString;
@property (nonatomic) IkatagosdkClient* _Nullable client;
@property (nonatomic) IkatagosdkKatagoRunner* _Nullable runner;
@end

/**
 * KatagoRunner represents katago runner
 */
@interface IkatagosdkKatagoRunner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * DisableCompress disables the compression
 */
- (void)disableCompress:(BOOL)noCompress;
/**
 * Run runs the katago
 */
- (BOOL)run:(id<IkatagosdkDataCallback> _Nullable)callback error:(NSError* _Nullable* _Nullable)error;
- (BOOL)runWithStdio:(NSString* _Nullable)command error:(NSError* _Nullable* _Nullable)error;
/**
 * SendGTPCommand sends the gtp command
 */
- (BOOL)sendGTPCommand:(NSString* _Nullable)command error:(NSError* _Nullable* _Nullable)error;
/**
 * SetClientID sets the client id
 */
- (void)setClientID:(NSString* _Nullable)clientID;
/**
 * SetExtraInfo sets the extra info
 */
- (void)setExtraInfo:(NSString* _Nullable)extraInfo;
/**
 * SetKataConfig sets the name of the kata config name
 */
- (void)setKataConfig:(NSString* _Nullable)kataConfig;
/**
 * SetKataLocalConfig sets the name of the kata local config file
 */
- (void)setKataLocalConfig:(NSString* _Nullable)kataLocalConfig;
/**
 * SetKataName sets the name of the katago name
 */
- (void)setKataName:(NSString* _Nullable)kataName;
/**
 * SetKataOverrideConfig sets the name of the kata override-config option of kata, example: analysisPVLen=30,playoutDoublingAdvantage=3
 */
- (void)setKataOverrideConfig:(NSString* _Nullable)kataOverrideConfig;
/**
 * SetKataWeight sets the name of the kata weight
 */
- (void)setKataWeight:(NSString* _Nullable)kataWeight;
/**
 * SetRefreshInterval sets the refresh interval
 */
- (void)setRefreshInterval:(long)refreshInterval;
/**
 * SetSubCommands sets the subcommands. for example: 'analysis -analysis-threads 12'
 */
- (void)setSubCommands:(NSString* _Nullable)subCommands;
/**
 * SetTransmitMoveNum sets the transmit move num
 */
- (void)setTransmitMoveNum:(long)transmitMoveNum;
/**
 * SetUseRawData sets if use the raw data or not
 */
- (void)setUseRawData:(BOOL)useRawData;
/**
 * Stop stops the katago engine
 */
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NewClient creates the new mobile client
 */
FOUNDATION_EXPORT IkatagosdkClient* _Nullable IkatagosdkNewClient(NSString* _Nullable world, NSString* _Nullable platform, NSString* _Nullable username, NSString* _Nullable password, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IkatagosdkClientRunner* _Nullable IkatagosdkNewClientRunnerFromArgs(NSString* _Nullable argString, NSError* _Nullable* _Nullable error);

@class IkatagosdkDataCallback;

/**
 * DataCallback defines the data callback
 */
@interface IkatagosdkDataCallback : NSObject <goSeqRefInterface, IkatagosdkDataCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)callback:(NSData* _Nullable)content;
- (void)onReady;
- (void)stderrCallback:(NSData* _Nullable)content;
@end

#endif
